version: 0.1

phases:
  build:
    commands:
      - echo Nothing to do yet
  install:
    runtime-versions:
      nodejs: 8
artifacts:
  files:
    - index.html
    - favicon.ico
    - styles/*
    - images/*